install.packages("lubridate")
install.packages("numbers")
install.packages("ggplot2")
install.packages("knitr")
install.packages("caTools")
install.packages("bitops")
install.packages("rprojroot")
install.packages("rmarkdown")
install.packages("reshape2")
install.packages("https://cran.r-project.org/src/contrib/Archive/cowplot/cowplot_0.9.4.tar.gz", repos = NULL, type = 'source')
install.packages("sf")
install.packages("raster")
install.packages("spData")
install.packages("devtools")
devtools::install_github("Nowosad/spDataLarge")
